dist: trusty
sudo: false
language: node_js
node_js:
  - "8"

cache: npm

jobs:
  include:
#    TODO: add tests and enable this stage
#    - stage: "Tests"
#      name: "unit tests"
#      script: npm run test:unit
    - stage: "Build"
      name: "build lib"
      script:
        - npm run build-lib
      deploy:
      - provider: script
        skip_cleanup: true
        script: npm run semantic-release
        on:
          branch: master
    - stage: "Release"
      if: branch = master
      script: npm run build-storybook
      deploy:
      - provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        keep_history: true
        local_dir: dist/docs

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
