dist: trusty
sudo: false
language: node_js
node_js:
  - "8"

cache: npm

jobs:
  include:
    - stage: "Tests"
      name: "unit tests"
      script: skip
    - stage: "Build"
      name: "build lib"
      script: npm run build-lib
      deploy:
      - provider: releases
        api_key: $GITHUB_TOKEN
        file: "dist/ngx-diagrams.zip"
        skip_cleanup: true
        on:
          tags: true
    - stage: "Release"
      if: branch = master
      script:
        - npm run build-storybook
        - npm run semantic-release
      deploy:
      - provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        keep-history: true
        local-dir: dist/docs
        on:
          tags: true

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
